2018-08-22 09:01:00,841- userDao.py:[line:19]- INFO - 用户名 123456 为空
2018-08-22 09:10:50,535- userDao.py:[line:19]- INFO - 用户名 123456 为空
2018-08-22 09:11:52,058- userDao.py:[line:19]- INFO - 用户名 123456 为空
2018-08-22 09:22:35,205- userDao.py:[line:19]- INFO - 用户名 123456 为空
2018-08-22 09:23:46,475- userDao.py:[line:19]- INFO - 用户名 123456 为空
2018-08-22 09:26:41,672- userDao.py:[line:19]- INFO - 用户名 123456 为空
2018-08-22 09:29:56,086- userDao.py:[line:19]- INFO - 用户名 123456 为空
2018-08-22 09:32:21,407- userDao.py:[line:19]- INFO - 用户名 123456 为空
2018-08-22 09:32:21,413- userDao.py:[line:43]- INFO - 用户123456用户绑定成功
2018-08-22 09:33:45,413- userDao.py:[line:22]- INFO - 用户名 123456 以解绑
2018-08-22 09:33:45,414- userDao.py:[line:44]- INFO - 用户123456用户绑定成功
2018-08-22 09:33:54,684- userDao.py:[line:22]- INFO - 用户名 123456 以解绑
2018-08-22 09:33:54,685- userDao.py:[line:44]- INFO - 用户123456用户绑定成功
2018-08-22 09:35:44,277- userDao.py:[line:22]- INFO - 用户名 123456 以解绑
2018-08-22 09:36:25,153- userDao.py:[line:44]- INFO - 用户123456用户绑定成功
2018-08-22 09:38:25,457- userDao.py:[line:22]- INFO - 用户名 123456 以解绑
2018-08-22 09:38:25,458- userDao.py:[line:43]- INFO - 用户123456用户绑定成功
2018-08-22 09:38:40,724- userDao.py:[line:22]- INFO - 用户名 123456 以解绑
2018-08-22 09:38:40,725- userDao.py:[line:43]- INFO - 用户123456用户绑定成功
2018-08-22 09:39:19,013- userDao.py:[line:22]- INFO - 用户名 123456 以解绑
2018-08-22 09:39:19,014- userDao.py:[line:43]- INFO - 用户123456用户绑定成功
2018-08-22 09:40:17,748- userDao.py:[line:19]- INFO - 用户名 123456 为空
2018-08-22 09:40:17,754- userDao.py:[line:43]- INFO - 用户123456用户绑定成功
2018-08-22 09:41:13,910- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:41:13,910- userDao.py:[line:40]- ERROR - 用户123456用户绑定失败
2018-08-22 09:41:59,419- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:41:59,419- userDao.py:[line:40]- ERROR - 用户123456用户绑定失败
2018-08-22 09:41:59,537- scoreDao.py:[line:44]- INFO - 用户123456数据库中无成绩
2018-08-22 09:41:59,540- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:43:24,313- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:43:24,314- userDao.py:[line:40]- ERROR - 用户123456用户绑定失败
2018-08-22 09:43:24,432- scoreDao.py:[line:44]- INFO - 用户123456数据库中无成绩
2018-08-22 09:43:24,434- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:43:31,593- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:43:31,593- userDao.py:[line:40]- ERROR - 用户123456用户绑定失败
2018-08-22 09:43:31,714- scoreDao.py:[line:44]- INFO - 用户123456数据库中无成绩
2018-08-22 09:43:31,716- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:46:30,021- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:46:30,022- userDao.py:[line:40]- ERROR - 用户123456用户绑定失败
2018-08-22 09:47:39,718- scoreDao.py:[line:44]- INFO - 用户123456数据库中无成绩
2018-08-22 09:48:16,340- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:48:16,340- userDao.py:[line:40]- ERROR - 用户123456用户绑定失败
2018-08-22 09:49:00,450- scoreDao.py:[line:44]- INFO - 用户123456数据库中无成绩
2018-08-22 09:49:46,058- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:51:53,302- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:51:53,303- userDao.py:[line:40]- ERROR - 用户123456用户绑定失败
2018-08-22 09:52:13,728- scoreDao.py:[line:44]- INFO - 用户123456数据库中无成绩
2018-08-22 09:54:06,317- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:57:27,735- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:57:27,735- userDao.py:[line:40]- ERROR - 用户123456用户绑定失败
2018-08-22 09:57:27,853- scoreDao.py:[line:44]- INFO - 用户123456数据库中无成绩
2018-08-22 09:57:27,855- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:57:55,337- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:57:55,337- userDao.py:[line:40]- ERROR - 用户123456用户绑定失败
2018-08-22 09:57:55,457- scoreDao.py:[line:44]- INFO - 用户123456数据库中无成绩
2018-08-22 09:57:55,460- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:57:57,113- scoreDao.py:[line:67]- INFO - 用户123456成绩更新成功
2018-08-22 09:57:57,115- scoreDao.py:[line:29]- INFO - 用户123456今天已经爬取过成绩
2018-08-22 09:57:57,115- scoreDao.py:[line:56]- INFO - 用户123456从数据库中取成绩
2018-08-22 09:59:01,057- userDao.py:[line:25]- INFO - 用户名 123456 以绑定
2018-08-22 09:59:01,057- userDao.py:[line:40]- ERROR - 用户123456用户绑定失败
2018-08-22 09:59:17,999- scoreDao.py:[line:29]- INFO - 用户123456今天已经爬取过成绩
2018-08-22 09:59:36,903- scoreDao.py:[line:56]- INFO - 用户123456从数据库中取成绩
